parameters:
  environmentObjects:
    - environmentName: 'dev'
      regionAbrvs: ['cus']
  loadTestConfigFile: ''
  secretsJSONObject: ''
  envJSONObject: ''


stages:
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
        - stage: '${{ parameters.serviceName }}_${{ environmentObject.environmentName}}_${{regionAbrv}}_bicep_deploy'
          jobs:
          - template: ../jobs/bicep_deploy_env_job.yml
            parameters:
              environmentName: ${{ environmentObject.environmentName }}
              loadTestConfigFile: ${{ parameters.loadTestConfigFile }}
              secretsJSONObject: ${{ parameters.secretsJSONObject }}
              envJSONObject: ${{ parameters.envJSONObject}}
              regionAbrv: ${{ regionAbrv }}
