parameters:
- name: azureSubscriptionName
  type: string
  default: ''
- name: actionOnUnmanage
  type: string
  default: 'deleteAll'
- name: denySettingsMode
  type: string
  default: 'denyDelete'
- name: deploymentStackName
  type: string
  default: ''
- name: deploymentStackDescription
  type: string
  default: 'Resource Group Deployment Stack'
- name: parametersFileName
  type: string
  default: 'parameters.json'
- name: inlineParameters
  type: string
  default: ''
- name: deploymentStackTags
  type: string
  default: ''
- name: templateFileName
  type: string
  default: 'main.bicep'
- name: command
  type: string
  default: 'validate'
- name: additionalArguments
  type: string
  default: ''
- name: deploymentResourceGroup
  type: string
  default: ''

steps:
- task: AzureCLI@2
  displayName: '${{ parameters.command }} deployment stack'
  inputs:
    azureSubscription: ${{ parameters.azureSubscriptionName }}
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az stack sub ${{ parameters.command }} --name ${{ parameters.deploymentStackName }} --action-on-unmanage ${{ parameters.actionOnUnmanage }} `
        --deny-settings-mode ${{ parameters.denySettingsMode }} --deployment-resource-group ${{ parameters.deploymentResourceGroup }}`
        --template-file '$(Agent.BuildDirectory)/${{parameters.templateFileName}}' --parameters '$(Agent.BuildDirectory)/${{parameters.parametersFileName}}' ${{ parameters.inlineParameters }} `
        --description "${{ parameters.deploymentStackDescription }}" ${{ parameters.additionalArguments }} `
        --tags ${{ parameters.deploymentStackTags }} --yes
