parameters:
- name: azureSubscriptionName
  type: string
  default: ''
- name: actionOnUnmanage
  type: string
  default: 'deleteAll'
- name: denySettingsMode
  type: string
  default: 'denyDelete'
- name: deploymentStackName
  type: string
  default: ''
- name: resourceGroupName
  type: string
  default: ''
- name: bypassStackOutOfSyncError
  type: boolean
  default: false
- name: denySettingsApplyToChildScopes
  type: boolean
  default: false
- name: denySettingsExcludedActions
  type: string
  default: ''
- name: denySettingsExcludedPrincipals
  type: string
  default: ''
- name: deploymentStackDescription
  type: string
  default: ''
- name: noWait
  type: boolean
  default: false
- name: parametersFileName
  type: string
  default: 'parameters.json'
- name: inlineParameters
  type: string
  default: ''
- name: deploymentStackTags
  type: string
  default: ''
- name: templateFileName
  type: string
  default: 'main.bicep'
- name: command
  type: string
  default: 'validate'
- name: additionalArguments
  type: string
  default: ''

steps:
- task: AzureCLI@2
  displayName: '${{ parameters.command }} deployment stack'
  inputs:
    azureSubscription: ${{ parameters.azureSubscriptionName }}
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az stack group ${{ parameters.command }} --name ${{ parameters.deploymentStackName }} --action-on-unmanage ${{ parameters.actionOnUnmanage }} `
        --deny-settings-mode ${{ parameters.denySettingsMode }} --resource-group ${{ parameters.resourceGroupName }} `
        --template-file ${{parameters.templateFileName}} --parameters ${{parameters.parametersFileName}} ${{ parameters.inlineParameters }} `
        --bse ${{ parameters.bypassStackOutOfSyncError }} --cs ${{ parameters.denySettingsApplyToChildScopes }} `
        --deny-settings-excluded-actions ${{ parameters.denySettingsExcludedActions }} --deny-settings-excluded-principals ${{ parameters.denySettingsExcludedPrincipals }} `
        --description ${{ parameters.deploymentStackDescription }} --no-wait ${{ parameters.noWait }}  ${{ parameters.additionalArguments }} `
        --tags ${{ parameters.deploymentStackTags }} --yes
