parameters:
- name: azureSubscriptionName
  type: string
  default: ''
- name: inlineScript
  type: string
  default: ''


steps:
- task: AzureCLI@2
  displayName: 'Azure CLI Inline Script'
  inputs:
    azureSubscription: ${{ parameters.azureSubscriptionName }}
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: '${{ parameters.inlineScript }} '
