parameters:
- name: azureSubscriptionName
  type: string
- name: inlineScript
  type: string
  default: ''
- name: errorActionPreference
  type: string
  default: 'stop'
- name: FailOnStandardError
  type: boolean
  default: false
- name: azurePowerShellVersion
  type: string
  default: 'LatestVersion'
- name: preferredAzurePowerShellVersion
  type: string
  default: '3.1.0'
- name: pwsh
  type: boolean
  default: false
- name: workingDirectory
  type: string
  default: ''
- name: displayName
  type: string
  default: 'Running Custom Azure PowerShell script from file'

steps:
- task: AzurePowerShell@5
  displayName: ${{ parameters.displayName }}
  inputs:
    scriptType: 'InlineScript'
    Inline: ${{ parameters.inlineScript }}
    ConnectedServiceNameARM: ${{ parameters.azureSubscriptionName }}
    errorActionPreference: ${{ parameters.errorActionPreference }}
    FailOnStandardError: ${{ parameters.FailOnStandardError }}
    azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
    pwsh: ${{ parameters.pwsh }}
    workingDirectory: ${{ parameters.workingDirectory }}
    
    
    
