parameters:
- name: sqlServerName
  type: string
  default: ''
- name: sqlDatabaseName
  type: string
  default: ''
- name: dacpacFilePath
  type: string
  default: ''
- name: authenticationType
  type: string
  default: 'servicePrincipal'
- name: ipDetectionMethod
  type: string
  default: 'AutoDetect'
- name: deployType
  type: string
  default: 'DacpacTask'
- name: deploymentAction
  type: string
  default: 'Publish'
- name: dacpacAdditionalArguments
  type: string
  default: ''
- name: deleteFirewallRule
  type: boolean
  default: true
- name: azureSubscription
  type: string
  default: ''

steps:
- task: SqlAzureDacpacDeployment@1
  displayName: 'Deploy ${{parameters.sqlDBName}} on ${{parameters.sqlServerName}}'
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    AuthenticationType: ${{ parameters.authenticationType }}
    ServerName: ${{ parameters.sqlServerName }}
    DatabaseName: ${{ parameters.sqlDatabaseName }}
    deployType: 'SqlTask'
    DacpacFile: ${{parameters.dacpacFilePath}}
    IpDetectionMethod: ${{ parameters.ipDetectionMethod }}
    AdditionalArguments: ${{ parameters.dacpacAdditionalArguments }}
    DeleteFirewallRule: ${{ parameters.deleteFirewallRule }}
