parameters:
- name: customCommand
  type: string
  default: ''
- name: packageDir
  type: string
  default: ''
steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: ${{ parameters.customCommand }}
    workingDir: ${{ parameters.packageDir }}
