parameters:
- name: serviceName
  type: string
- name: TerraformDirectory
  type: string
- name: backendServiceAws
  type: string
- name: backendAwsRegion
  type: string
- name: TerraformStateStorageAccountName
  type: string

  
steps:
  - task: TerraformCLI@1
    displayName: 'Terraform : init'
    inputs:
      command: init
      backendType: aws
      workingDirectory: ${{ parameters.TerraformDirectory }}
      backendServiceAws: ${{ parameters.backendServiceAws }}
      backendAwsRegion: ${{ parameters.backendAwsRegion }}
      backendAwsBucket: ${{ parameters.TerraformStateStorageAccountName }}
      backendAwsKey: ${{ parameters.serviceName }}.tfstate
