parameters:
- name: serviceName
  type: string
  default: ''
- name: environmentName
  type: string
  default: cicd
- name: dependsOn
  type: object
  default: []
- name: projectName
  type: string  
jobs:
- job: '${{ parameters.serviceName }}_delete_ade'
  dependsOn: ${{ parameters.dependsOn }}
  variables:
  - template: ../variables/azure_${{ parameters.environmentName }}_variables.yml
  steps:
  - template: ../tasks/azcli_inline_script_task.yml
    parameters:
      displayName: 'Destroy ADE Environment'
      inlineScript: 'az devcenter dev environment delete --project-name ${{ parameters.projectName }} --name ${{ parameters.serviceName }}${{ parameters.environmentName }} --yes --user-id ${{ variables.azureServiceConnectionUserID }}'
      azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
