parameters:
- name: packageDir
  type: string
  default: ''
- name: dataFactoryResourceID
  type: string
  default: ''
- name: regionAbrv
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''
- name: environmentName
  type: string
  default: ''
jobs:
- job: 'adf_${{ parameters.serviceName }}_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}_build'
  steps:
    - template: ../tasks/node_install_task.yml
    - template: ../tasks/npm_install_task.yml
      parameters:
        packageDir: ${{ parameters.packageDir }}
    - template: ../tasks/npm_custom_command_task.yml
      parameters:
        packageDir: ${{ parameters.packageDir }}
        customCommand: 'run build export ${{ parameters.packageDir }} ${{ parameters.dataFactoryResourceID }} "Infrastructure"'
    - template: ../tasks/ado_publish_pipeline_task.yml
      parameters:
        targetPath: ${{ parameters.packageDir }}
        artifactName: 'ADFTemplates'
