parameters:
- name: environmentName
  type: string
- name: serviceName
  type: string
- name: regionAbrv
  type: string
- name: location
  type: string
  default: 'eastus'
- name: templateFile
  type: string
- name: templateParametersFile
  type: string
- name: overrideParameters
  type: string
  default: ''
- name: artifactName
  type: string
  default: 'ADFTemplates'
- name: stopStartTriggersScriptName
  type: string
  default: 'PrePostDeploymentScript.ps1'

jobs:
- deployment: '${{ parameters.serviceName }}_infrastructure_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  environment: ${{ parameters.environmentName }}
  variables: 
  - template: ../variables/azure_${{parameters.environmentName}}_variables.yml
  - template: ../variables/azure_global_variables.yml
  - name: deploymentName
    value: '${{ parameters.serviceName }}_infrastructure_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  - name: resourceGroupName
    value: '${{ variables.resourceGroupAbrv }}-${{ parameters.serviceName }}-${{ parameters.environmentName }}-${{ parameters.regionAbrv }}'
  - name: dataFactoryName
    value: '${{ variables.dataFactoryAbrv }}-${{ parameters.serviceName }}-${{ parameters.environmentName }}-${{ parameters.regionAbrv }}'
  strategy:
    runOnce:
        deploy:
            steps:
            - powershell: Get-ChildItem -Path $(Agent.BuildDirectory) -recurse
            - template: ../tasks/azpwsh_file_execute_task.yml
              parameters:
                azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
                scriptPath: '../${{ parameters.artifactName }}/${{ parameters.stopStartTriggersScriptName }}'
                ScriptArguments: '-armTemplate "$(System.DefaultWorkingDirectory)/${{ parameters.artifactName }}" -ResourceGroupName ${{ variables.resourceGroupName }} -DataFactoryName ${{ variables.dataFactoryName }} -predeployment $true -deleteDeployment $false'
                displayName: 'Stop ADF Triggers'
                workingDirectory: $(Agent.BuildDirectory) 
            - template: ../tasks/ado_ARM_deployment_task.yml
              parameters:
               azureResourceManagerConnection: ${{ variables.azureServiceConnectionName }}
               resourceGroupName: ${{ variables.resourceGroupName }}
               location: ${{ parameters.location }}
               csmFile: '${{ parameters.artifactName }}/${{ parameters.templateFile }}'
               csmParametersFile: '${{ parameters.artifactName }}/parameters/${{ parameters.environmentName }}.${{ parameters.regionAbrv }}.${{ parameters.templateParametersFile }}.json'
               overrideParameters: ${{ parameters.overrideParameters }}
            - template: ../tasks/azpwsh_file_execute_task.yml
              parameters:
                azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
                scriptPath: '${{ parameters.artifactName }}/${{ parameters.stopStartTriggersScriptName }}'
                ScriptArguments: '-armTemplate "$(System.DefaultWorkingDirectory)/${{ parameters.artifactName }}" -ResourceGroupName ${{ variables.resourceGroupName }} -DataFactoryName ${{ variables.dataFactoryName }} -predeployment $false -deleteDeployment $true'
                displayName: 'Start ADF Triggers'
                workingDirectory: $(Agent.BuildDirectory) 
