parameters:
- name: workingDir
  type: string
  default: ''
- name: dataFactoryResourceID
  type: string
  default: ''
- name: regionAbrv
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''
- name: environmentName
  type: string
  default: ''
jobs:
- job: 'adf_${{ parameters.serviceName }}_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}_build'
  steps:
    - template: ../tasks/node_install_task.yml
    - template: ../tasks/npm_install_task.yml
      parameters:
        workingDir: ${{ parameters.workingDir }}
    - template: ../tasks/npm_custom_command_task.yml
      parameters:
        workingDir: ${{ parameters.workingDir }}
        customCommand: 'run build validate ${{ parameters.workingDir }} ${{ parameters.dataFactoryResourceID }}'
    - template: ../tasks/npm_custom_command_task.yml
      parameters:
        workingDir: ${{ parameters.workingDir }}
        customCommand: 'run build export ${{ parameters.workingDir }} ${{ parameters.dataFactoryResourceID }} "ArmTemplate"'
    - template: ../tasks/ado_publish_pipeline_task.yml
      parameters:
        artifactName: 'df_${{ parameters.serviceName }}_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
