parameters:
- name: environmentName
  type: string
- name: serviceName
  type: string
- name: regionAbrv
  type: string
- name: location
  type: string
  default: 'eastus'
- name: templateFile
  type: string
- name: templateParametersFile
  type: string
- name: overrideParameters
  type: string
  default: ''
- name: artifactName
  type: string
  default: 'ADFTemplates'
- name: stopStartTriggersScriptName
  type: string
  default: 'PrePostDeploymentScript.ps1'
- name: workingDirectory
  type: string
  default: '../'



jobs:
- deployment: '${{ parameters.serviceName }}_adfPipelines_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  environment: ${{ parameters.environmentName }}
  dependsOn: '${{ parameters.serviceName }}_infrastructure_lt_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  variables: 
  - template: ../variables/azure_${{parameters.environmentName}}_variables.yml
  - template: ../variables/azure_global_variables.yml
  - name: deploymentName
    value: '${{ parameters.serviceName }}_adfPipelines_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  - name: resourceGroupName
    value: '${{ variables.resourceGroupAbrv }}-${{ parameters.serviceName }}-${{ parameters.environmentName }}-${{ parameters.regionAbrv }}'
  - name: dataFactoryName
    value: '${{ variables.dataFactoryAbrv }}-${{ parameters.serviceName }}-${{ parameters.environmentName }}-${{ parameters.regionAbrv }}'
  - name: powerShellScriptPath
    value: '../${{ parameters.artifactName }}/${{ parameters.stopStartTriggersScriptName }}'
  - name: ARMTemplatePath
    value: '${{ parameters.artifactName }}/${{ parameters.templateFile }}'
  - name: linkedServiceStorageAccount
    value: 'lt$(Build.BuildId)'
  - name: linkedServiceStorageAccountName
    value: ${{ variables.storageAccountAbrv }}${{ variables.linkedServiceStorageAccount }}${{ parameters.environmentName }}${{ parameters.regionAbrv }}
  - name: linkedServiceStorageAccountContainerName
    value: 'templates'
  - name: linkedServiceStorageAccountURL
    value: 'https://${{ variables.linkedServiceStorageAccountName }}.blob.core.windows.net/${{ variables.linkedServiceStorageAccountContainerName }}'
  - name: dependentSASToken
    value: $[ dependencies.${{ parameters.serviceName }}_infrastructure_lt_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}.outputs['setVariable.sasToken'] ]
    
  strategy:
    runOnce:
        deploy:
            steps:
             - template: ../tasks/azpwsh_file_execute_task.yml
               parameters:
                displayName: 'Stop ADF Triggers'
                azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
                scriptPath: ${{ variables. powerShellScriptPath }}
                ScriptArguments: '-armTemplate "${{ parameters.artifactName }}/ARMTemplateForFactory.json" -ResourceGroupName ${{ variables.resourceGroupName }} -DataFactoryName ${{ variables.dataFactoryName }} -predeployment $true -deleteDeployment $false'
                workingDirectory: ${{ parameters.workingDirectory }}
             - template: ../tasks/ado_ARM_linked_template_deployment_task.yml
               parameters:
                azureResourceManagerConnection: ${{ variables.azureServiceConnectionName }}
                resourceGroupName: ${{ variables.resourceGroupName }}
                location: ${{ parameters.location }}
                csmFileLink: '${{ variables.linkedServiceStorageAccountURL }}/${{ parameters.templateFile }}$(dependentSASToken)'
                csmParametersFileLink: '${{ variables.linkedServiceStorageAccountURL }}/parameters/${{ parameters.environmentName }}.${{ parameters.regionAbrv }}.${{ parameters.templateParametersFile }}.json$(dependentSASToken)'
                overrideParameters: '${{ parameters.overrideParameters }} -containerUri ${{ variables.linkedServiceStorageAccountURL }}/linkedTemplates -containerSasToken $(dependentSASToken)'
             - template: ../tasks/azpwsh_file_execute_task.yml
               parameters:
                displayName: 'Start ADF Triggers'
                azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
                scriptPath: ${{ variables. powerShellScriptPath }}
                ScriptArguments: '-armTemplate "${{ variables.ARMTemplatePath }}" -ResourceGroupName ${{ variables.resourceGroupName }} -DataFactoryName ${{ variables.dataFactoryName }} -predeployment $false -deleteDeployment $true'
                workingDirectory: ${{ parameters.workingDirectory }}
             - template: ../tasks/azcli_inline_script_task.yml
               parameters:
                displayName: 'Delete Storage Account'
                inlineScript: 'az storage account delete --name ${{ variables.storageAccountAbrv }}${{ variables.linkedServiceStorageAccount }}${{ parameters.environmentName }}${{ parameters.regionAbrv }} --resource-group ${{ variables.resourceGroupName }} --yes'
                azureSubscriptionName: ${{ variables.azureServiceConnectionName }}

