parameters:
- name: environmentName
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''
- name: activityName
  type: string
  default: 'run_inline_powershell_script'
- name: regionAbrv
  type: string
  default: ''
- name: dependsOn
  type: object
  default: []
- name: inlineScript
  type: string
  default: ''
- name: errorActionPreference
  type: string
  default: 'stop'
- name: FailOnStandardError
  type: boolean
  default: false
- name: azurePowerShellVersion
  type: string
  default: 'LatestVersion'
- name: preferredAzurePowerShellVersion
  type: string
  default: '3.1.0'
- name: pwsh
  type: boolean
  default: false
- name: workingDirectory
  type: string
  default: ''
- name: jobCondition
  type: string
  default: 'succeeded()'
jobs:
- deployment: '${{ parameters.serviceName }}_${{ parmameters.activityName }}_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  environment: ${{ parameters.environmentName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.jobCondition }}
  variables: 
  - template: ../variables/azure_${{parameters.environmentName}}_variables.yml
  - template: ../variables/azure_global_variables.yml
  strategy:
    runOnce:
        deploy:
            steps:
            - task: AzurePowerShell@5
              displayName: Running Custom Azure PowerShell script from file
              inputs:
                scriptType: 'InlineScript'
                Inline: ${{ parameters.inlineScript }}
                ConnectedServiceNameARM: ${{ variables.azureServiceConnectionName }}
                errorActionPreference: ${{ parameters.errorActionPreference }}
                FailOnStandardError: ${{ parameters.FailOnStandardError }}
                azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
                pwsh: ${{ parameters.pwsh }}
                workingDirectory: ${{ parameters.workingDirectory }}
