parameters:
- name: environmentName
  type: string
- name: templateFileName
  type: string
- name: templateDirectory
  type: string
- name: serviceName
  type: string
- name: regionAbrv
  type: string
- name: infrastructureHasSecrets
  type: boolean
  default: false
- name: infrastructureSecrets
  type: object
  default: false
- name: dependsOn
  type: object
  default: []
- name: paramExt
  type: string
  default: '.json'
- name: deployStack
  type: string
  default: 'false'
- name: overrideParameters 
  type: string
  default: ''
jobs:
- deployment: '${{ parameters.serviceName }}_infrastructure_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  environment: ${{ parameters.environmentName }}
  dependsOn: ${{ parameters.dependsOn }}
  variables: 
  - template: ../variables/azure_${{parameters.environmentName}}_variables.yml
  - template: ../variables/azure_global_variables.yml
  - template: ../variables/azure_${{ parameters.regionAbrv }}_variables.yml
  - name: deploymentName
    value: '${{ parameters.serviceName }}_infrastructure_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  - ${{ if eq(parameters.infrastructureHasSecrets, true)}} :
    - group: ${{ parameters.serviceName }}_${{ variables.keyVaultAbrv }}_${{ parameters.environmentName }}
  - name: templateFileName
    value: '$(Pipeline.Workspace)/${{ parameters.templateDirectory }}/${{ parameters.templateFileName }}.bicep'
  - name: parametersFileName
    value: '$(Pipeline.Workspace)/${{ parameters.templateDirectory }}/parameters/${{ parameters.environmentName }}.${{ parameters.regionAbrv }}.parameters${{ parameters.paramExt }}'


  strategy:
    runOnce:
        deploy:
            steps:

            - template: ../tasks/azcli_sub_deploy_task.yml
              parameters:
                  azureSubscriptionName: ${{ variables.azureServiceConnectionName}}
                  templateFileName: ${{ variables.templateFileName }}
                  parametersFileName: ${{ variables.parametersFileName }}
                  command: 'what-if'
                  additionalArguments: '--out yamlc'
                  deploymentName: ${{ variables.deploymentName }}
                  location: ${{ variables.location }}
            - ${{ if eq( parameters.deployStack, 'true') }}:
               - template: ../tasks/azcli_stack_deployment_sub_create.yml
                 parameters:
                   azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
                   deploymentStackName: ${{ parameters.serviceName }}_deploymentStack_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}
                   templateFileName: ${{ variables.templateFileName }}
                   parametersFileName: ${{ variables.parametersFileName }}
                   additionalArguments: ${{ parameters.overrideParameters }}
                   command: 'create'
                   location: ${{ variables.location }}
            - ${{ else }}:
                - template: ../tasks/azcli_sub_deploy_task.yml
                  parameters:
                      azureSubscriptionName: ${{ variables.azureServiceConnectionName}}
                      templateFileName: ${{ variables.templateFileName }}
                      parametersFileName: ${{ variables.parametersFileName }}
                      command: 'create'
                      deploymentName: ${{ variables.deploymentName }}
                      additionalArguments: ${{ parameters.overrideParameters }}
                      location: ${{ variables.location }}


