parameters:
- name: environmentName
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''
- name: regionAbrv
  type: string
  default: ''
- name: dependsOn
  type: object
  default: []
- name: sqlServerName
  type: string
  default: ''
- name: sqlDatabaseName
  type: string
  default: ''
- name: dacpacFilePath
  type: string
  default: ''
- name: authenticationType
  type: string
  default: 'servicePrincipal'
- name: ipDetectionMethod
  type: string
  default: 'AutoDetect'
- name: resourceGroupName
  type: string
  default: ''
- name: deployType
  type: string
  default: 'DacpacTask'
- name: dacpacAdditionalArguments
  type: string
  default: ''

jobs:
- deployment: '${{ parameters.serviceName }}_app_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  environment: ${{ parameters.environmentName }}
  dependsOn: ${{ parameters.dependsOn }}
  variables: 
  - template: ../variables/azure_${{parameters.environmentName}}_variables.yml
  - template: ../variables/azure_global_variables.yml
  - name: deploymentName
    value: '${{ parameters.serviceName }}_app_deploy_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  - name: sqlServerName
    value: '${{ variables.sqlServerAbrv }}-${{ parameters.sqlServerName }}-${{ parameters.environmentName }}-${{ parameters.regionAbrv }}${{ variables.sqlServerURLSuffix }}'
  - name: sqlDatabaseName
    value: '${{ variables.sqlServerAbrv }}${{ parameters.sqlDatabaseName }}'
  strategy:
    runOnce:
        deploy:
            steps:
            - template: ../tasks/dacpac_dacpac_deploy_task.yml
              parameters:
                azureSubscription: ${{ variables.azureServiceConnectionName }}
                sqlServerName: ${{ variables.sqlServerName }}
                sqlDatabaseName: ${{ variables.sqlDatabaseName }}
                authenticationType: ${{ parameters.authenticationType }}
                ipDetectionMethod: ${{ parameters.ipDetectionMethod }}
                dacpacFilePath: '${{ parameters.dacpacFilePath }}'
                deploymentAction: 'DeployReport'
                deleteFirewallRule: false
            - template: ../tasks/ado_copy_files_task.yml
              parameters:
                # $SqlDeploymentOutputFile is defined in https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1 since output path is hardcoded
                sourceFolder: 'GeneratedOutputFiles'
                targetFolder: 'postDeploy/${{ variables.sqlServerName }}/${{ variables.sqlDatabaseName }}'
            - template: ../tasks/dacpac_dacpac_deploy_task.yml
              parameters:
                azureSubscription: ${{ variables.azureServiceConnectionName }}
                sqlServerName: ${{ variables.sqlServerName }}
                sqlDatabaseName: ${{ variables.sqlDatabaseName }}
                authenticationType: ${{ parameters.authenticationType }}
                ipDetectionMethod: ${{ parameters.ipDetectionMethod }}
                dacpacFilePath: '${{ parameters.dacpacFilePath }}'
                deployType: ${{ parameters.deployType }}
                deploymentAction: 'Publish'
                dacpacAdditionalArguments: ${{ parameters.dacpacAdditionalArguments }}
                
