parameters:
- name: azureSubscriptionName
  type: string
  default: ''
- name: loadTestConfigFile
  type: string
  default: ''
- name: loadTestResourceName
  type: string
  default: ''
- name: secretsJSONObject
  type: string
  default: ''
- name: envJSONObject
  type: string
  default: ''
- name: regionAbrv
  type: string
  default: ''
- name: environmentName
  type: string
  default: ''
  
jobs:
- job: 'run_azure_load_test_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  steps:
    - template: ../tasks/azure_load_test_task.yml
      parameters:
        azureSubscriptionName: ${{ parameters.azureSubscriptionName }}
        loadTestConfigFile: ${{ parameters.loadTestConfigFile }}
        loadTestResourceGroupName: ${{ parameters.loadTestResourceGroupName }}
        loadTestResourceName: ${{ parameters.loadTestResourceName }}
        secretsJSONObject: ${{ parameters.secretsJSONObject }}
        secrets: ${{ parameters.secretsJSONObject }}
        env: ${{ parameters.envJSONObject }}
