parameters:
- name: serviceName
  type: string
  default: ''
- name: projectFile
  type: string
  default: '**/*.sln'
- name: msbuildLocationMethod
  type: string
  default: 'version'
- name: msbuildVersion
  type: string
  default: 'latest'
- name: msbuildArchitecture
  type: string
  default: 'x86'
- name: platform
  type: string
  default: 'AnyCPU'
- name: configuration
  type: string
  default: ''
- name: msbuildArguments
  type: string
  default: ''
- name: clean
  type: boolean
  default: false
- name: maximumCpuCount
  type: boolean
  default: false
- name: restoreNugetPackages
  type: boolean
  default: false
- name: logProjectEvents
  type: boolean
  default: false
- name: createLogFile
  type: boolean
  default: false
- name: logFileVerbosity
  type: string
  default: 'normal'
- name: srcFileFolder
  type: string
  default: 'src'

jobs:
- job: 'msbuild_${{ paramaters.serviceName }}'
  steps:
  - template: ../tasks/msbuild_project_build_task.yml
    parameters:
        solution: ${{ parameters.srcFilePath }}/${{ parameters.projectFile }}
        msbuildLocationMethod: ${{ parameters.msbuildLocationMethod }}
        msbuildVersion: ${{ parameters.msbuildVersion }}
        msbuildArchitecture: ${{ parameters.msbuildArchitecture }}
        platform: ${{ parameters.platform }}
        configuration: ${{ parameters.configuration }}
        msbuildArguments: ${{ parameters.msbuildArguments }}
        clean: ${{ parameters.clean }}
        maximumCpuCount: ${{ parameters.maximumCpuCount }}
        restoreNugetPackages: ${{ parameters.restoreNugetPackages }}
        logProjectEvents: ${{ parameters.logProjectEvents }}
        createLogFile: ${{parameters.createLogFile }}
        logFileVerbosity: ${{ parameters.logFileVerbosity }}
  - template: ../tasks/ado_publish_pipeline_task.yml
    parameters:
      artifactName: sql
      targetPath: drop
  
