parameters:
- name: serviceName
  type: string
  default: ''
- name: sourceFolder
  default: '$(Build.SorcesDirectory)'
jobs:
- job: '${{ parameters.serviceName }}_build'
  variables:
  - targetFolder: '$(Build.ArtifactStagingDirectory/${{ parameters.serviceName }}_npm'
  steps:
  - template: ../tasks/node_install_task.yml
  - template: ../tasks/npm_install_task.yml
  - template: ../tasks/cmd_execute_task.yml
    parameters:
      scriptContent: 'npm run build'
      dsiplayName: 'npm build'
  - template: ../tasks/ado_copy_files_task.yml
    parameters:
      sourceFolder: ${{ parameters.sourceFolder }}
      contents: '*.tgz'
      targetFolder: ${{ variables.targetFolder }}
  - template: ../tasks/ado_copy_files_task.yml
    parameters:
      sourceFolder: ${{ parameters.sourceFolder }}
      contents: 'package.json'
      targetFolder: ${{ variables.targetFolder }}
  - template: ../tasks/ado_publish_pipeline_task.yml
    parameters:
      targetPath: ${{ variables.targetFolder }}
      artifact: '${{ parameters.serviceName }}_npm'
      
