parameters:
- name: serviceName
  type: string
  default: ''
- name: sourceFolder
  default: '$(Build.SourcesDirectory)'
jobs:
- job: '${{ parameters.serviceName }}_build'
  variables:
    targetFolder: '$(Build.ArtifactStagingDirectory/${{ parameters.serviceName }}_npm'
  steps:
  - template: ../tasks/node_install_task.yml
  - template: ../tasks/ado_cache_task.yml
  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm build'
  - powershell: Get-ChildItem -Path ${{ parameters.sourceFolder }} -recurse | Get-Member
  - template: ../tasks/ado_copy_files_task.yml
    parameters:
      sourceFolder: ${{ parameters.sourceFolder }}
      contents: '*.tgz' 
      targetFolder: ${{ variables.targetFolder }}
  - template: ../tasks/ado_copy_files_task.yml
    parameters:
      sourceFolder: ${{ parameters.sourceFolder }}
      contents: 'package.json'
      targetFolder: ${{ variables.targetFolder }}
  - template: ../tasks/ado_publish_pipeline_task.yml
    parameters:
      targetPath: ${{ variables.targetFolder }}
      artifactName: '${{ parameters.serviceName }}_npm'
      
