parameters:
- name: pipelineName
  type: string
  default: 'AppPipeline'
- name: environmentName
  type: string
  default: 'prd'
  
jobs:
- job: retain_${{ parameters.pipelineName }}_${{ parameters.environmentName }}
  steps:
  - template: ../tasks/ado_retain_pipeline_task.yml