parameters:
- name: serviceName
  type: string
  default: ''
- name: synapseDirectory 
  type: string
  default: ''
- name: targetWorkspaceName
  type: string
  default: ''
- name: azureSubscription
  type: string
  default: ''
- name: resourceGroupName
  type: string
  default: ''
jobs:
- job: 'synapse_${{ parameters.serviceName }}_build'
  steps:
    - template: ../tasks/synapse_build_task.yml
      parameters:
        targetWorkspaceName: ${{ parameters.targetWorkspaceName }}
        synapseDirectory: ${{ parameters.synapseDirectory  }}
        azureSubscription: ${{ parameters.azureSubscription }} 
        resourceGroupName: ${{ parameters.resourceGroupName }}
