parameters:
- name: environmentName
  type: string
  default: 'dev'
- name: serviceName
  type: string
- name: terraformVersion
  type: string
  default: 'latest'
- name: additionalParameters
  type: object
  default: []
- name: dependsOn
  type: object
  default: []
jobs:
- job: 'buildTerraform_${{ parameters.environmentName }}'
  dependsOn: ${{parameters.dependsOn}}
  displayName: Build Terraform ${{ parameters.environmentName }}
  variables:
  - template: ../variables/aws_terraform_${{ parameters.environmentName }}_variables.yml
  steps:
  - template: ../tasks/terraform_install_task.yml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: ../tasks/terraform_init_aws_task.yml
    parameters:
     serviceName: ${{ parameters.serviceName }}
     TerraformDirectory: ${{ variables.workingDirectory  }}
     backendServiceAws: ${{ variables.backendServiceAws }}
     backendAwsRegion: ${{ variables.backendAwsRegion }}
     backendAwsBucket: ${{ variables.backendAwsBucket }}


