parameters:
- name: packageForLinux
  type: string
  default: ''
- name: inLineScript
  type: string
  default: ''
- name: environmentName
  type: string
  default: ''
- name: serviceName
  type: string
  default: ''
- name: regionAbrv
  type: string
  default: ''
- name: dependsOn
  type: object
  default: []
- name: webAppType
  type: string
  default: 'webApp'
- name: delayInMinutes
  type: string
  default: '1'

jobs:
- deployment: '${{ parameters.serviceName }}_app_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  environment: ${{ parameters.environmentName }}
  dependsOn: ${{ parameters.dependsOn }}
  variables: 
  - template: ../variables/azure_${{parameters.environmentName}}_variables.yml
  - template: ../variables/azure_global_variables.yml
  - name: deploymentName
    value: '${{ parameters.serviceName }}_app_deploy_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
  - name: webAppName
    value: '${{ variables.webAppAbrv }}-${{ parameters.serviceName }}-${{ parameters.environmentName }}-${{ parameters.regionAbrv }}'
  - name: secondsToPause
    value: 60
  strategy:
    runOnce:
        deploy:
            steps:
            - template: ../tasks/azpwsh_inline_execute_task.yml
              parameters:
                azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
                inlineScript: 'Start-Sleep -Seconds ${{ parameters.secondsToPause }}'
                displayName: 'Pause for ${{ parameters.secondsToPause }} Previous Infrastructure Job Deployment'
            - template: ../tasks/ado_webapp_deploy_task.yml
              parameters:
                azureSubscriptionName: ${{ variables.azureServiceConnectionName }}
                WebAppName:  ${{ variables.webAppName }}
                packageForLinux: ${{ parameters.packageForLinux }}
                InlineScript: ${{ parameters.inLineScript }}
                webAppType: ${{ parameters.webAppType }}
