parameters:
- name: templateDirectory
  type: string 
  default: 'infrastructure'
- name: serviceName
  type: string
  default: 'SampleApp'
- name: adeObjects
  type: object
- name: loadTestConfigFile
  type: string
  default: ''
- name: secretsJSONObject
  type: string
  default: ''
- name: envJSONObject
  type: string
  default: ''
- name: loadTestResourceName
  type: string
  default: ''
- name: loadTestResourceGroupName
  type: string
  
stages:
- stage: '${{ parameters.serviceName }}_ade_build'
    - ${{ each adeObject in parameters.adeObjects }} :
      - ${{ each regionAbrv in adeObject.regionAbrvs }} :
        jobs:
        - template: ../jobs/ade_create_env_job.yml
          parameters:
            templateDirectory: ${{ adeObject.templateDirectory }}
            devCenterName: ${{ adeObject.devCenterName }}
            projectName: ${{ adeObject.projectName }}
            catalogName: ${{ adeObject.catalogName }}
            environmentDefinitionName: ${{ adeObject.environmentDefinitionName }}
            enviornmentType: ${{ adeObject.environmentType }}
            regionAbrv: ${{ regionAbrv }}
            serviceName: ${{ parameters.serviceName }}
            templateDirectory: ${{ parameters.templateDirectory }}
        - template: ../jobs/load_test_execute_job.yml
          parameters:
            loadTestConfigFile: ${{ parameters.loadTestConfigFile }}
            secretsJSONObject: ${{ parameters.secretsJSONObject }}
            envJSONObject: ${{ parameters.envJSONObject}}
            regionAbrv: ${{ parameters.regionAbrv }}
            loadTestResourceGroupName: ${{ parameters.loadTestResourceGroupName }}
            loadTestResourceName: ${{ parameters.loadTestResourceName }}
            dependsOn: ['${{ parameters.serviceName }}_create_ade']
        - template: ../jobs/ade_create_env_job.yml
          parameters:
            adeObjects: ${{ parameters.adeObjects }}
            serviceName: ${{ parameters.serviceName }}
            dependsOn: ['run_azure_load_test_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}']
    
