parameters:
- name: templateDirectory
  type: string 
  default: 'infrastructure'
- name: serviceName
  type: string
  default: 'SampleApp'
- name: adeObjects
  type: object
- name: loadTestConfigFile
  type: string
  default: ''
- name: secretsJSONObject
  type: string
  default: ''
- name: envJSONObject
  type: string
  default: ''
- name: loadTestResourceName
  type: string
  default: ''
- name: loadTestResourceGroupName
  type: string
- name: environmentName
  type: string
  
stages:
- stage: '${{ parameters.serviceName }}_ade_build'
  jobs:
  - ${{ each adeObject in parameters.adeObjects }} :
    - ${{ each regionAbrv in adeObject.regionAbrvs }} :
        - template: ../jobs/ade_create_env_job.yml
          parameters:
            templateDirectory: ${{ parameters.templateDirectory }}
            devCenterName: ${{ adeObject.devCenterName }}
            projectName: ${{ adeObject.projectName }}
            catalogName: ${{ adeObject.catalogName }}
            environmentDefinitionName: ${{ adeObject.environmentDefinitionName }}
            environmentType: ${{ adeObject.environmentType }}
            regionAbrv: ${{ regionAbrv }}
            serviceName: ${{ parameters.serviceName }}
            environmentName: ${{ parameters.environmentName }}
        - template: ../jobs/load_test_execute_job.yml
          parameters:
            environmentName: ${{ parameters.environmentName }}
            loadTestConfigFile: ${{ parameters.loadTestConfigFile }}
            secretsJSONObject: ${{ parameters.secretsJSONObject }}
            envJSONObject: ${{ parameters.envJSONObject}}
            regionAbrv: ${{ regionAbrv }}
            loadTestResourceGroupName: ${{ parameters.loadTestResourceGroupName }}
            loadTestResourceName: ${{ parameters.loadTestResourceName }}
            dependsOn: ['${{ parameters.serviceName }}_${{ regionAbrv }}_create_ade']
        - template: ../jobs/ade_destroy_env_job.yml
          parameters:
            serviceName: ${{ parameters.serviceName }}
            projectName: ${{ adeObject.projectName }}
            regionAbrv: ${{ parameters.regionAbrv }}
            environmentName: ${{ parameters.environmentName }}
            dependsOn: ['run_azure_load_test_${{ parameters.environmentName }}_${{ regionAbrv }}']
    
