parameters:
- name: templateDirectory
  type: string 
  default: 'infrastructure'
- name: serviceName
  type: string
  default: 'SampleApp'
- name: adeObjects
  type: object
  
stages:
- stage: '${{ parameters.serviceName }}_ade_build'
  jobs:
  - template: ../jobs/ade_create_env_job.yml
    parameters:
      adeObjects: ${{ parameters.adeObjects }}
      serviceName: ${{ parameters.serviceName }}
      templateDirectory: ${{ parameters.templateDirectory }}
  - template: ../jobs/load_test_execute_job.yml
    parameters:
      environmentName: ${{ parameters.environmentName }}
      loadTestConfigFile: ${{ parameters.loadTestConfigFile }}
      secretsJSONObject: ${{ parameters.secretsJSONObject }}
      envJSONObject: ${{ parameters.envJSONObject}}
      regionAbrv: ${{ parameters.regionAbrv }}
      loadTestResourceGroupName: ${{ parameters.loadTestResourceGroupName }}
      loadTestResourceName: ${{ parameters.loadTestResourceName }}
  - template: ../jobs/ade_create_env_job.yml
    parameters:
      adeObjects: ${{ parameters.adeObjects }}
      serviceName: ${{ parameters.serviceName }}
    
