parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
      regionAbrvs: ['cus']
      subscriptionId: ''
- name: serviceName
  type: string
  default: 'SampleApp'
- name: packageDir
  type: string
  default: '$(Build.Repository.LocalPath)/adf_scripts'
- name: adfDir
  type: string
  default: 'adf'
stages:
- stage: '${{ parameters.serviceName }}_build'
  variables:
  - template: ../variables/azure_global_variables.yml
  jobs:
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
      - template: ../jobs/adf_build_job.yml
        parameters:
          environmentName: ${{ environmentObject.environmentName }}
          dataFactoryResourceID: '/subscriptions/${{ environmentObject.subscriptionID }}/resourceGroups/${{ variables.resourceGroupAbrv }}-${{ parameters.serviceName }}-${{ environmentObject.environmentName }}-${{ regionAbrv }}/providers/Microsoft.DataFactory/factories/${{ variables.dataFactoryAbrv }}-${{ parameters.serviceName }}-${{ environmentObject.environmentName }}-${{ regionAbrv }}'
          serviceName: ${{ parameters.serviceName }}
          regionAbrv: ${{ regionAbrv }}
          packageDir: ${{ parameters.packageDir }}
          adfDir: ${{ parameters.adfDir }}
