parameters:
  regionAbrvs: '[cus]'
  environmentName: ''
  templateFileName: ''
  templateDirectory: 'Infrastructure'
  serviceName: ''
  dependsOnEnv: ''
  infrastructureHasSecrets: false
  infrastructureSecrets: []

stages:
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
        - stage: '${{ parameters.serviceName }}_${{ environmentObject.environmentName}}_${{regionAbrv}}_bicep_deploy'
          jobs:
          - template: ../jobs/bicep_deploy_env_job.yml
            parameters:
              environmentName: ${{ environmentObject.environmentName }}
              templateFileName: ${{ parameters.templateFile }}
              templateDirectory: ${{ parameters.templateDirectory }}
              serviceName: ${{ parameters.serviceName}}
              regionAbrv: ${{ regionAbrv }}
              infrastructureHasSecrets: ${{ parameters.infrastructureHasSecrets }}
              infrastructureSecrets: ${{ parameters.infrastructureSecrets}}
