parameters:
  regionAbrvs: '[cus]'
  environmentName: ''
  templateFile: ''
  templateDirectory: 'Infrastructure'
  serviceName: ''
  dependsOnEnv: ''
  infrastructureHasSecrets: false
  infrastructureSecrets: []
  appName: ''

stages:
- ${{ each regionAbrv in parameters.regionAbrvs }} :
  - stage: deploy_${{ parameters.serviceName }}_${{parameters.environmentName }}_${{ regionAbrv }}
    variables: 
      ${{ if eq(parameters.dependsOnEnv,'' )}} :
        dependsOnEnv: '${{ parameters.serviceName }}_build'
      ${{ else }}:
        dependsOnEnv: 'deploy_${{ parameters.serviceName }}_${{parameters.dependsOnEnv}}_${{ regionAbrv }}'
    dependsOn: ${{ variables.dependsOnEnv }}
    
    jobs:
    - template: ../jobs/bicep_deploy_env_job.yml
      parameters:
        environmentName: ${{ parameters.environmentName }}
        templateFile: ${{ parameters.templateFile }}
        templateDirectory: ${{ parameters.templateDirectory }}
        serviceName: ${{ parameters.serviceName}}
        regionAbrv: ${{ regionAbrv }}
        infrastructureHasSecrets: ${{ parameters.infrastructureHasSecrets }}
        infrastructureSecrets: ${{ parameters.infrastructureSecrets}}
        appName: ${{ parameters.appName }}
