parameters:
  environmentObjects:
    - environmentName: 'dev'
      regionAbrvs: ['cus']
  templateFileName: ''
  templateDirectory: 'Infrastructure'
  serviceName: ''
  dependsOnEnv: ''
  infrastructureHasSecrets: false
  infrastructureSecrets: []
  deploymentScope: 'subscription'
  bicepParamExt: false
stages:
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
        - stage: '${{ parameters.serviceName }}_${{ environmentObject.environmentName}}_${{regionAbrv}}_bicep_deploy'
          variables:
          - name: bicepParamString
            ${{ if eq(parameters.bicepParamExt, true)}} :
              value: '.bicepparam'
            ${{ else }} :
              value: '.json'
          jobs:
          - ${{ if eq(parameters.deploymentScope, 'subscription')}} :
            - template: ../jobs/bicep_deploy_env_job.yml
              parameters:
                environmentName: ${{ environmentObject.environmentName }}
                templateFileName: ${{ parameters.templateFileName }}
                templateDirectory: ${{ parameters.templateDirectory }}
                serviceName: ${{ parameters.serviceName}}
                regionAbrv: ${{ regionAbrv }}
                infrastructureHasSecrets: ${{ parameters.infrastructureHasSecrets }}
                infrastructureSecrets: ${{ parameters.infrastructureSecrets}}
                paramExt: ${{ variables.bicepParamString }}
          - ${{ elseif eq(parameters.deploymentScope, 'resourceGroup')}} : 
            - template: ../jobs/arm_rg_deploy_env_job.yml
              parameters:
                environmentName: ${{ environmentObject.environmentName }}
                templateFileName: ${{ parameters.templateFileName }}
                templateDirectory: ${{ parameters.templateDirectory }}
                serviceName: ${{ parameters.serviceName}}
                regionAbrv: ${{ regionAbrv }}
                infrastructureHasSecrets: ${{ parameters.infrastructureHasSecrets }}
                infrastructureSecrets: ${{ parameters.infrastructureSecrets}}
                paramExt: ${{ variables.bicepParamString }}
