parameters:
- name: projectConfigurations
  type: object
  default:
      environmentName: 'dev'
      regionAbrvs: ['cus']
      sqlServerName: ''
      sqlDBName: ''
      authenticationType: 'servicePrincipal'
      ipDetectionMethod: 'AutoDetect'
      deployType: 'DacpacTask'
- name: serviceName
  type: string
  default: ''


stages:

  - ${{ each projectConfiguration in parameters.projectConfigurations }} :
    - ${{ each regionAbrv in projectConfiguration.regionAbrvs }} :
        - stage: '${{ parameters.serviceName }}_${{ projectConfiguration.environmentName}}_${{regionAbrv}}_dacpac_deploy'
          jobs:
          - template: ../jobs/dacpac_dacpac_env_job.yml
            parameters:
              environmentName: ${{ projectConfiguration.environmentName }}
              serviceName: ${{ parameters.serviceName}}
              regionAbrv: ${{ regionAbrv }}
              sqlServerName: ${{ projectConfiguration.sqlServerName }}
              sqlDBName: ${{ projectConfiguration.sqlDBName }}
              authenticationType: ${{ projectConfiguration.authenticationType }}
              ipDetectionMethod: ${{ projectConfiguration.ipDetectionMethod }}
              deployType: ${{ projectConfiguration.deployType }}
              dacpacFilePath: ${{ projectConfiguration.sqlDBName }}/*.dacpac
                
