parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
      regionAbrvs: ['cus']
- name: loadTestConfigFile
  type: string
  default: ''
- name: secretsJSONObject
  type: string
  default: ''
- name: envJSONObject
  type: string
  default: ''
- name: loadTestResourceName
  type: string
  default: ''
- name: loadTestResourceGroupName
  type: string
  default: ''


stages:
  - ${{ each environmentObject in parameters.environmentObjects }} :
    - ${{ each regionAbrv in environmentObject.regionAbrvs }} :
        - stage: '${{ parameters.serviceName }}_${{ environmentObject.environmentName}}_${{regionAbrv}}_bicep_deploy'
          jobs:
          - template: ../jobs/load_test_execute_job.yml
            parameters:
              environmentName: ${{ environmentObject.environmentName }}
              loadTestConfigFile: ${{ parameters.loadTestConfigFile }}
              secretsJSONObject: ${{ parameters.secretsJSONObject }}
              envJSONObject: ${{ parameters.envJSONObject}}
              regionAbrv: ${{ regionAbrv }}
              loadTestResourceGroupName: ${{ parameters.loadTestResourceGroupName }}
              loadTestResourceName: ${{ parameters.loadTestResourceName }}
