parameters:
  serviceName: ''
  projectNamesConfigurations:
    - projectName: ''
      projectExtension: '.csproj'
      platform: 'AnyCPU'
      configuration: ''
      msbuildArguments: ''
      logFileVerbosity: 'normal'
  artifactsToPublish: ['infrastructure']
  msbuildLocationMethod: 'version'
  msbuildVersion: 'latest'
  msbuildArchitecture: 'x86'
  maximumCpuCount: false
stages:
- stage: '${{ parameters.serviceName }}_build'
  variables:
    solutionPath: '$(Build.SourcesDirectory)/${{ parameters.solutionName }}/'
  jobs:
  - ${{ each artifactToPublish in parameters.artifactsToPublish }} :
    - template: ../jobs/artifact_publish_job.yml
      parameters:
        targetPath: ${{ artifactToPublish }}
        artifactname: ${{ artifactToPublish }}
           
  - ${{ each projectNamesConfiguration in parameters.projectNamesConfigurations }} :
    - template: ../jobs/msbuild_build_job.yml
      parameters:
          serviceName: ${{ projectNamesConfiguration.projectName }}
          projectFile: ${{ projectNamesConfiguration.projectName }}${{ projectNamesConfiguration.projectExtension }}
          msbuildLocationMethod: ${{ parameters.msbuildLocationMethod }}
          msbuildVersion: ${{ parameters.msbuildVersion }}
          msbuildArchitecture: ${{ parameters.msbuildArchitecture }}
          platform: ${{ projectNamesConfiguration.platform }}
          configuration: ${{ projectNamesConfiguration.configuration }}
          msbuildArguments: ${{ projectNamesConfiguration.msbuildArguments }}
          logFileVerbosity: ${{ projectNamesConfiguration.logFileVerbosity }}
