parameters:
- name: serviceName
  type: string
  default: 'SampleApp'
- name: synapseDirectory
  type: string
  default: '$(Build.Repository.LocalPath)/synapse'
- name: targetWorkspaceName
  default: 'synapse'
stages:
- stage: '${{ parameters.serviceName }}_build'
  variables:
  jobs:
    - template: ../jobs/synapse_build_job.yml
      parameters:
        serviceName: ${{ parameters.serviceName }}
        synapseDirectory: ${{ parameters.synapseDirectory }}
        targetWorkspaceName: ${{ parameters.targetWorkspaceName }}
